version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: tts_backend
    volumes:
      - ./backend/generated:/app/generated
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - tts_network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: tts_frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8000
    networks:
      - tts_network

networks:
  tts_network:
    driver: bridge
